# Generated by Django 4.2.27 on 2025-12-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mods', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod'),
        ),
    ]
