# Generated by Django 4.2.27 on 2025-12-15 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['mod', 'ip_address', 'timestamp'], name='analytics_d_mod_id_32ef9b_idx'),
        ),
    ]
