# Generated by Django 4.2.27 on 2025-12-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='downloadlog',
            name='analytics_d_mod_id_32ef9b_idx',
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['mod', 'timestamp'], name='analytics_d_mod_id_3f5bca_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['ip_address'], name='analytics_d_ip_addr_8d3387_idx'),
        ),
    ]
