# Generated by Django 4.2.27 on 2025-12-17 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('uploader_name', models.CharField(default='Anonymous', help_text='Name displayed as the uploader', max_length=100)),
                ('youtube_url', models.URLField(blank=True, help_text='Embed link for video preview', null=True)),
                ('version', models.CharField(blank=True, help_text='e.g. 1.0', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mod_images/')),
                ('is_cover', models.BooleanField(default=False)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mods.mod')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. ShareMods, Google Drive', max_length=100)),
                ('url', models.URLField()),
                ('file_size', models.CharField(help_text='e.g. 250 MB', max_length=50)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='mods.mod')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Guest', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mods.mod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
