# Generated by Django 4.2.27 on 2025-12-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='uploader_email',
            field=models.EmailField(blank=True, help_text='Private email for contact/tracking', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mod',
            name='uploader_ip',
            field=models.GenericIPAddressField(blank=True, help_text="Uploader's IP address", null=True),
        ),
    ]
