# Generated by Django 4.2.27 on 2025-12-15 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mods', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modimage',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mods.mod'),
        ),
        migrations.AddField(
            model_name='mod',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mod',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mods', to='categories.category'),
        ),
        migrations.AddField(
            model_name='mod',
            name='game_versions',
            field=models.ManyToManyField(related_name='compatible_mods', to='mods.gameversion'),
        ),
        migrations.AddField(
            model_name='mod',
            name='required_dlcs',
            field=models.ManyToManyField(blank=True, related_name='required_by_mods', to='mods.dlc'),
        ),
        migrations.AddField(
            model_name='collection',
            name='mods',
            field=models.ManyToManyField(related_name='collections', to='mods.mod'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mod',
            index=models.Index(fields=['status', 'created_at'], name='mods_mod_status_6b542e_idx'),
        ),
        migrations.AddIndex(
            model_name='mod',
            index=models.Index(fields=['average_rating'], name='mods_mod_average_343a21_idx'),
        ),
    ]
