# Generated by Django 4.2.27 on 2025-12-15 19:03

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mods', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mod',
            name='conflicts_with',
            field=models.ManyToManyField(blank=True, help_text='Mods known to crash with this one', to='mods.mod'),
        ),
        migrations.AddField(
            model_name='mod',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='mods/files/'),
        ),
        migrations.AddField(
            model_name='mod',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mod',
            name='min_game_version',
            field=models.CharField(default='1.0', help_text='e.g., 1.48', max_length=20),
        ),
        migrations.CreateModel(
            name='ModVersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20)),
                ('changelog', models.TextField()),
                ('file', models.FileField(upload_to='mods/archive/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='mods.mod')),
            ],
        ),
        migrations.CreateModel(
            name='ModScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='mods.mod')),
            ],
        ),
    ]
