# Generated by Django 4.2.27 on 2025-12-17 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_mod_uploader_email_mod_uploader_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 means no rating given', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='mod',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mod',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mod',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
