# Generated by Django 4.2.27 on 2025-12-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0003_mod_approved_by_mod_conflicts_with_mod_file_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mod',
            index=models.Index(fields=['download_count'], name='mods_mod_downloa_6f8f15_idx'),
        ),
        migrations.AddIndex(
            model_name='mod',
            index=models.Index(fields=['is_approved'], name='mods_mod_is_appr_8eb9f5_idx'),
        ),
    ]
