# Generated by Django 4.2.27 on 2025-12-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0004_mod_mods_mod_downloa_6f8f15_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mod',
            name='mods_mod_is_appr_8eb9f5_idx',
        ),
        migrations.AlterField(
            model_name='mod',
            name='conflicts_with',
            field=models.ManyToManyField(blank=True, to='mods.mod'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='file_size',
            field=models.CharField(blank=True, help_text='Auto-calculated or manual (e.g., 250 MB)', max_length=50),
        ),
        migrations.AlterField(
            model_name='mod',
            name='file_url',
            field=models.URLField(blank=True, help_text='External download link', null=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
