# Generated by Django 4.2.27 on 2025-12-17 11:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_icon'),
        ('mods', '0005_remove_mod_mods_mod_is_appr_8eb9f5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Guest', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. ShareMods, Google Drive', max_length=100)),
                ('url', models.URLField()),
                ('file_size', models.CharField(help_text='e.g. 250 MB', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='mods',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='modscreenshot',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='modversionhistory',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='report',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.AlterModelOptions(
            name='mod',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='mod',
            name='mods_mod_status_6b542e_idx',
        ),
        migrations.RemoveIndex(
            model_name='mod',
            name='mods_mod_average_343a21_idx',
        ),
        migrations.RemoveIndex(
            model_name='mod',
            name='mods_mod_downloa_6f8f15_idx',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='conflicts_with',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='file',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='game_versions',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='min_game_version',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='required_dlcs',
        ),
        migrations.AddField(
            model_name='mod',
            name='uploader_name',
            field=models.CharField(default='Anonymous', help_text='Name displayed as the uploader', max_length=100),
        ),
        migrations.AddField(
            model_name='mod',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Embed link for video preview', null=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mod',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mod',
            name='version',
            field=models.CharField(blank=True, help_text='e.g. 1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='modimage',
            name='image',
            field=models.ImageField(upload_to='mod_images/'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='DLC',
        ),
        migrations.DeleteModel(
            name='GameVersion',
        ),
        migrations.DeleteModel(
            name='ModScreenshot',
        ),
        migrations.DeleteModel(
            name='ModVersionHistory',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='downloadlink',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='mods.mod'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mods.mod'),
        ),
    ]
