# Generated by Django 4.2.27 on 2025-12-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mods', '0001_initial'),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mods.mod'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forums.comment'),
        ),
    ]
